baseURL = 'https://lepigeonbaladeur.github.io/photography/'
languageCode = 'fr-fr'
title = 'Le_Pigeon_Baladeur_Photography'
theme = "PaperMod"

[outputs]
    home = ["HTML"]
    page = ["HTML"]
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]

[params]
    # On dÃ©sactive ces options pour voir si le build passe
    ShowShareButtons = false
    ShowReadingTime = false
    ShowPostNavLinks = false
    ShowBreadCrumbs = false
    ShowCodeCopyButtons = false

[params.profileMode]
    enabled = true
    title = "Salut, c'est Le Pigeon Baladeur ðŸ‘‹"
    subtitle = "Sur mon site, je partage mes photos. En ce moment, je prends des photos avec un Samsung S25 Ultra. Je ne suis pas spÃ©cialiste en photographie, mais j'aime beaucoup capturer ce que je vois. Câ€™est pourquoi je voulais vous montrer mes photos ici."
    imageUrl = "images/logo.webp"
    imageTitle = "Ma photo de profil"
    imageWidth = 150
    imageHeight = 150
    [[params.profileMode.buttons]]
            name = "Voir mes photos ðŸ“·"
            url = "/photos/"
